// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  bento: defineAsyncComponent(() => import("./Bento/index.vue")),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  case_studies: defineAsyncComponent(() => import("./CaseStudies/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  integrations: defineAsyncComponent(() => import("./Integrations/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  showcase: defineAsyncComponent(() => import("./Showcase/index.vue")),
});
